package codegen.pass;

import codegen.FunctionTable;
import codegen.IREmitter;
import codegen.LLVMTypes;
import codegen.Value;
import codegen.VariableScopes;
import generated.CParser;
import generated.CParserBaseVisitor;
import java.util.ArrayList;
import java.util.List;
import org.antlr.v4.runtime.tree.ParseTree;

// 翻译单元与函数定义的代码生成
public class FunctionPass {

    private final CParserBaseVisitor<Value> walker;
    private final IREmitter ir;
    private final VariableScopes vars;
    private final FunctionTable functions;

    public FunctionPass(CParserBaseVisitor<Value> walker, IREmitter ir,
                        VariableScopes vars, FunctionTable functions) {
        this.walker = walker;
        this.ir = ir;
        this.vars = vars;
        this.functions = functions;
    }

    public Value translationUnit(CParser.TranslationUnitContext ctx) {
        ir.raw("; generated by CompilerC\n");
        ir.raw("target triple = \"x86_64-pc-linux-gnu\"\n\n");
        // 先登记所有函数签名，再生成函数体，这样允许函数互相调用
        for (ParseTree child : ctx.children) {
            if (child instanceof CParser.FunctionDefContext f) {
                String name = f.ID().getText();
                List<String> params = new ArrayList<>();
                if (f.paramList() != null) {
                    for (CParser.ParamContext p : f.paramList().param()) {
                        params.add(LLVMTypes.of(p.typeSpecifier().getText()));
                    }
                }
                functions.define(name, LLVMTypes.of(f.typeSpecifier().getText()), params);
            }
        }
        vars.enterScope(); // 全局作用域
        walker.visitChildren(ctx);
        return null;
    }

    public Value functionDef(CParser.FunctionDefContext ctx) {
        String name = ctx.ID().getText();
        String retType = functions.returnTypeOf(name);
        functions.setCurrentReturnType(retType);

        List<CParser.ParamContext> params =
                ctx.paramList() == null ? List.of() : ctx.paramList().param();
        StringBuilder sig = new StringBuilder();
        sig.append("define ").append(retType).append(" @").append(name).append("(");
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sig.append(", ");
            sig.append(functions.paramTypesOf(name).get(i)).append(" %").append(params.get(i).ID().getText());
        }
        sig.append(") {\n");
        ir.raw(sig.toString());
        ir.emitLabel("entry");

        vars.enterScope();
        for (CParser.ParamContext p : params) {
            String type = LLVMTypes.of(p.typeSpecifier().getText());
            String addr = "%" + p.ID().getText() + ".addr";
            ir.emit(addr + " = alloca " + type);
            ir.emit("store " + type + " %" + p.ID().getText() + ", ptr " + addr);
            vars.define(p.ID().getText(), new Value(type, addr));
        }
        walker.visit(ctx.compoundStmt());
        vars.exitScope();

        if (!ir.isTerminated()) {
            ir.emit("void".equals(retType) ? "ret void" : "ret " + retType + " 0");
        }
        ir.raw("}\n\n");
        return null;
    }
}
