package codegen;

import generated.CParser;
import generated.CParserBaseVisitor;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.ParseTree;

// 代码生成主类：把语法树翻译成 LLVM IR。
// IR 输出委托给 IREmitter，类型映射委托给 LLVMTypes，变量地址委托给 VariableScopes，
// 本类只保留"每类语法节点翻译成什么指令模板"的逻辑。
public class CodeGenerator extends CParserBaseVisitor<Value> {

    private final IREmitter ir = new IREmitter();
    private final VariableScopes vars = new VariableScopes();
    private final Map<String, String> funcRetTypes = new HashMap<>();
    private final Map<String, List<String>> funcParamTypes = new HashMap<>();
    private final Deque<String> breakLabels = new ArrayDeque<>();
    private String currentRetType = "i32";

    public String getIR() {
        return ir.getIR();
    }

    // ── 顶层结构 ──

    @Override
    public Value visitTranslationUnit(CParser.TranslationUnitContext ctx) {
        ir.raw("; generated by CompilerC\n");
        ir.raw("target triple = \"x86_64-pc-linux-gnu\"\n\n");
        // 先登记所有函数签名，再生成函数体，这样允许函数互相调用
        for (ParseTree child : ctx.children) {
            if (child instanceof CParser.FunctionDefContext f) {
                String name = f.ID().getText();
                funcRetTypes.put(name, LLVMTypes.of(f.typeSpecifier().getText()));
                List<String> params = new ArrayList<>();
                if (f.paramList() != null) {
                    for (CParser.ParamContext p : f.paramList().param()) {
                        params.add(LLVMTypes.of(p.typeSpecifier().getText()));
                    }
                }
                funcParamTypes.put(name, params);
            }
        }
        vars.enterScope(); // 全局作用域
        visitChildren(ctx);
        return null;
    }

    @Override
    public Value visitFunctionDef(CParser.FunctionDefContext ctx) {
        String name = ctx.ID().getText();
        currentRetType = funcRetTypes.get(name);

        List<CParser.ParamContext> params =
                ctx.paramList() == null ? List.of() : ctx.paramList().param();
        StringBuilder sig = new StringBuilder();
        sig.append("define ").append(currentRetType).append(" @").append(name).append("(");
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sig.append(", ");
            sig.append(funcParamTypes.get(name).get(i)).append(" %").append(params.get(i).ID().getText());
        }
        sig.append(") {\n");
        ir.raw(sig.toString());
        ir.emitLabel("entry");

        vars.enterScope();
        for (CParser.ParamContext p : params) {
            String type = LLVMTypes.of(p.typeSpecifier().getText());
            String addr = "%" + p.ID().getText() + ".addr";
            ir.emit(addr + " = alloca " + type);
            ir.emit("store " + type + " %" + p.ID().getText() + ", ptr " + addr);
            vars.define(p.ID().getText(), new Value(type, addr));
        }
        visit(ctx.compoundStmt());
        vars.exitScope();

        if (!ir.isTerminated()) {
            ir.emit("void".equals(currentRetType) ? "ret void" : "ret " + currentRetType + " 0");
        }
        ir.raw("}\n\n");
        return null;
    }

    @Override
    public Value visitCompoundStmt(CParser.CompoundStmtContext ctx) {
        vars.enterScope();
        for (CParser.StatementContext s : ctx.statement()) {
            if (ir.isTerminated()) break; // return 之后的死代码不再生成
            visit(s);
        }
        vars.exitScope();
        return null;
    }

    // ── 声明 ──

    @Override
    public Value visitDeclaration(CParser.DeclarationContext ctx) {
        String type = LLVMTypes.of(ctx.typeSpecifier().getText());
        String name = ctx.ID().getText();
        String addr = ir.allocaName(name);

        if (ctx.IntConst() != null) {
            // 数组：分配一整块 [N x 元素类型]
            String arrayType = "[" + ctx.IntConst().getText() + " x " + type + "]";
            ir.emit(addr + " = alloca " + arrayType);
            vars.define(name, new Value(type, addr, arrayType));
            return null;
        }

        ir.emit(addr + " = alloca " + type);
        vars.define(name, new Value(type, addr));

        if (ctx.expr() != null) {
            Value v = LLVMTypes.convert(ir, visit(ctx.expr()), type);
            ir.emit("store " + type + " " + v.ref + ", ptr " + addr);
        }
        return null;
    }

    // ── 语句 ──

    @Override
    public Value visitReturnStmt(CParser.ReturnStmtContext ctx) {
        if (ctx.expr() == null || "void".equals(currentRetType)) {
            ir.emit("ret void");
        } else {
            Value v = LLVMTypes.convert(ir, visit(ctx.expr()), currentRetType);
            ir.emit("ret " + currentRetType + " " + v.ref);
        }
        ir.markTerminated();
        return null;
    }

    @Override
    public Value visitBreakStmt(CParser.BreakStmtContext ctx) {
        ir.emit("br label %" + breakLabels.peek());
        ir.markTerminated();
        return null;
    }

    @Override
    public Value visitIfStmt(CParser.IfStmtContext ctx) {
        Value cond = LLVMTypes.toI1(ir, visit(ctx.expr()));
        String thenL = ir.newLabel("if.then");
        String contL = ir.newLabel("if.cont");
        boolean hasElse = ctx.statement().size() > 1;
        String elseL = hasElse ? ir.newLabel("if.else") : contL;

        ir.emit("br i1 " + cond.ref + ", label %" + thenL + ", label %" + elseL);

        ir.emitLabel(thenL);
        visit(ctx.statement(0));
        if (!ir.isTerminated()) ir.emit("br label %" + contL);

        if (hasElse) {
            ir.emitLabel(elseL);
            visit(ctx.statement(1));
            if (!ir.isTerminated()) ir.emit("br label %" + contL);
        }
        ir.emitLabel(contL);
        return null;
    }

    @Override
    public Value visitWhileStmt(CParser.WhileStmtContext ctx) {
        String condL = ir.newLabel("while.cond");
        String bodyL = ir.newLabel("while.body");
        String endL = ir.newLabel("while.end");

        ir.emit("br label %" + condL);
        ir.emitLabel(condL);
        Value cond = LLVMTypes.toI1(ir, visit(ctx.expr()));
        ir.emit("br i1 " + cond.ref + ", label %" + bodyL + ", label %" + endL);

        ir.emitLabel(bodyL);
        breakLabels.push(endL);
        visit(ctx.statement());
        breakLabels.pop();
        if (!ir.isTerminated()) ir.emit("br label %" + condL);

        ir.emitLabel(endL);
        return null;
    }

    @Override
    public Value visitForStmt(CParser.ForStmtContext ctx) {
        String condL = ir.newLabel("for.cond");
        String bodyL = ir.newLabel("for.body");
        String endL = ir.newLabel("for.end");

        vars.enterScope(); // init 里声明的变量只在循环内可见
        if (ctx.init != null) visit(ctx.init);

        ir.emit("br label %" + condL);
        ir.emitLabel(condL);
        if (ctx.cond != null) {
            Value cond = LLVMTypes.toI1(ir, visit(ctx.cond));
            ir.emit("br i1 " + cond.ref + ", label %" + bodyL + ", label %" + endL);
        } else {
            ir.emit("br label %" + bodyL); // 无条件 = 死循环
        }

        ir.emitLabel(bodyL);
        breakLabels.push(endL);
        visit(ctx.statement());
        breakLabels.pop();
        if (!ir.isTerminated()) {
            if (ctx.post != null) visit(ctx.post); // 步进表达式在循环体之后、回到条件之前
            ir.emit("br label %" + condL);
        }

        ir.emitLabel(endL);
        vars.exitScope();
        return null;
    }

    @Override
    public Value visitForInit(CParser.ForInitContext ctx) {
        if (ctx.declaration() != null) visit(ctx.declaration());
        else if (ctx.expr() != null) visit(ctx.expr());
        return null;
    }

    @Override
    public Value visitExprStmt(CParser.ExprStmtContext ctx) {
        if (ctx.expr() != null) visit(ctx.expr());
        return null;
    }

    // ── 表达式叶子 ──

    @Override
    public Value visitIntExpr(CParser.IntExprContext ctx) {
        return new Value("i32", ctx.getText());
    }

    @Override
    public Value visitFloatExpr(CParser.FloatExprContext ctx) {
        double d = Double.parseDouble(ctx.getText());
        return new Value("float", String.format("%e", d));
    }

    @Override
    public Value visitCharExpr(CParser.CharExprContext ctx) {
        String inner = ctx.getText().substring(1, ctx.getText().length() - 1);
        int code;
        if (inner.charAt(0) != '\\') {
            code = inner.charAt(0);
        } else {
            code = switch (inner.charAt(1)) {
                case 'n' -> '\n';
                case 't' -> '\t';
                case '0' -> 0;
                default  -> inner.charAt(1);
            };
        }
        return new Value("i32", String.valueOf(code));
    }

    @Override
    public Value visitIdExpr(CParser.IdExprContext ctx) {
        Value var = vars.lookup(ctx.ID().getText());
        String t = ir.newTemp();
        ir.emit(t + " = load " + var.type + ", ptr " + var.ref);
        return new Value(var.type, t);
    }

    @Override
    public Value visitParenExpr(CParser.ParenExprContext ctx) {
        return visit(ctx.expr());
    }

    // ── 运算 ──

    private Value binary(CParser.ExprContext left, CParser.ExprContext right, String op) {
        Value l = visit(left);
        Value r = visit(right);
        boolean isFloat = "float".equals(l.type) || "float".equals(r.type);
        String type = isFloat ? "float" : "i32";
        l = LLVMTypes.convert(ir, l, type);
        r = LLVMTypes.convert(ir, r, type);

        String inst = switch (op) {
            case "+" -> isFloat ? "fadd" : "add";
            case "-" -> isFloat ? "fsub" : "sub";
            case "*" -> isFloat ? "fmul" : "mul";
            case "/" -> isFloat ? "fdiv" : "sdiv";
            case "%" -> isFloat ? "frem" : "srem";
            default -> throw new IllegalStateException("未知运算符: " + op);
        };
        String t = ir.newTemp();
        ir.emit(t + " = " + inst + " " + type + " " + l.ref + ", " + r.ref);
        return new Value(type, t);
    }

    private Value comparison(CParser.ExprContext left, CParser.ExprContext right, String op) {
        Value l = visit(left);
        Value r = visit(right);
        boolean isFloat = "float".equals(l.type) || "float".equals(r.type);
        String type = isFloat ? "float" : "i32";
        l = LLVMTypes.convert(ir, l, type);
        r = LLVMTypes.convert(ir, r, type);

        String pred = switch (op) {
            case "<"  -> isFloat ? "olt" : "slt";
            case "<=" -> isFloat ? "ole" : "sle";
            case ">"  -> isFloat ? "ogt" : "sgt";
            case ">=" -> isFloat ? "oge" : "sge";
            case "==" -> isFloat ? "oeq" : "eq";
            case "!=" -> isFloat ? "one" : "ne";
            default -> throw new IllegalStateException("未知比较: " + op);
        };
        String t = ir.newTemp();
        ir.emit(t + " = " + (isFloat ? "fcmp " : "icmp ") + pred + " " + type + " " + l.ref + ", " + r.ref);
        String z = ir.newTemp();
        ir.emit(z + " = zext i1 " + t + " to i32");
        return new Value("i32", z);
    }

    @Override
    public Value visitAddSub(CParser.AddSubContext ctx) {
        return binary(ctx.expr(0), ctx.expr(1), ctx.op.getText());
    }

    @Override
    public Value visitMulDiv(CParser.MulDivContext ctx) {
        return binary(ctx.expr(0), ctx.expr(1), ctx.op.getText());
    }

    @Override
    public Value visitCompare(CParser.CompareContext ctx) {
        return comparison(ctx.expr(0), ctx.expr(1), ctx.op.getText());
    }

    @Override
    public Value visitEquality(CParser.EqualityContext ctx) {
        return comparison(ctx.expr(0), ctx.expr(1), ctx.op.getText());
    }

    @Override
    public Value visitAssignExpr(CParser.AssignExprContext ctx) {
        Value var = vars.lookup(ctx.ID().getText());
        Value v = LLVMTypes.convert(ir, visit(ctx.expr()), var.type);
        ir.emit("store " + var.type + " " + v.ref + ", ptr " + var.ref);
        return v;
    }

    // 计算数组元素的地址：getelementptr [N x T], ptr %arr, i32 0, i32 %idx
    private Value arrayAddress(Token nameTok, CParser.ExprContext indexExpr) {
        Value var = vars.lookup(nameTok.getText());
        Value idx = LLVMTypes.convert(ir, visit(indexExpr), "i32");
        String p = ir.newTemp();
        ir.emit(p + " = getelementptr " + var.arrayType + ", ptr " + var.ref + ", i32 0, i32 " + idx.ref);
        return new Value(var.type, p);
    }

    @Override
    public Value visitArrayAccess(CParser.ArrayAccessContext ctx) {
        Value addr = arrayAddress(ctx.ID().getSymbol(), ctx.expr());
        String t = ir.newTemp();
        ir.emit(t + " = load " + addr.type + ", ptr " + addr.ref);
        return new Value(addr.type, t);
    }

    @Override
    public Value visitArrayAssign(CParser.ArrayAssignContext ctx) {
        Value addr = arrayAddress(ctx.ID().getSymbol(), ctx.expr(0));
        Value v = LLVMTypes.convert(ir, visit(ctx.expr(1)), addr.type);
        ir.emit("store " + addr.type + " " + v.ref + ", ptr " + addr.ref);
        return v;
    }

    @Override
    public Value visitPostInc(CParser.PostIncContext ctx) {
        // 支持 x++ 和 arr[i]++，先取地址
        Value addr;
        if (ctx.expr() instanceof CParser.IdExprContext id) {
            Value var = vars.lookup(id.ID().getText());
            addr = new Value(var.type, var.ref);
        } else if (ctx.expr() instanceof CParser.ArrayAccessContext arr) {
            addr = arrayAddress(arr.ID().getSymbol(), arr.expr());
        } else {
            throw new RuntimeException("++ 只支持变量或数组元素");
        }
        String oldV = ir.newTemp();
        ir.emit(oldV + " = load " + addr.type + ", ptr " + addr.ref);
        String newV = ir.newTemp();
        ir.emit(newV + " = add " + addr.type + " " + oldV + ", 1");
        ir.emit("store " + addr.type + " " + newV + ", ptr " + addr.ref);
        return new Value(addr.type, oldV); // 后缀 ++ 返回旧值
    }

    @Override
    public Value visitCallExpr(CParser.CallExprContext ctx) {
        String name = ctx.ID().getText();
        String retType = funcRetTypes.get(name);
        List<String> paramTypes = funcParamTypes.get(name);

        StringBuilder args = new StringBuilder();
        int i = 0;
        for (CParser.ExprContext e : ctx.expr()) {
            Value v = LLVMTypes.convert(ir, visit(e), paramTypes.get(i));
            if (i > 0) args.append(", ");
            args.append(paramTypes.get(i)).append(" ").append(v.ref);
            i++;
        }
        String t = ir.newTemp();
        ir.emit(t + " = call " + retType + " @" + name + "(" + args + ")");
        return new Value(retType, t);
    }
}
